apiVersion: v1
data:
  uri: CHANGE_ME
  api-key: CHANGE_ME
  provider: b3BlbmFp  # openai
  type: b3BlbmFp  # openai
kind: Secret
metadata:
  name: genai-creds
type: servicebinding.io/ai

---
apiVersion: services.tanzu.vmware.com/v1
kind: PreProvisionedService
metadata:
  name: genai
spec:
  bindingConnectors:
  - name: main
    description: Gen AI credentials
    type: openai
    secretRef:
      name: genai-creds
